version: '3.4'
services:
  # Lokale Datenbank - Virtuoso
  database:
    image: tenforce/virtuoso:virtuoso7.2.5
    volumes:
      - ./images/database/data/virtuoso:/data
    ports:
      - "8890:8890"
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://localhost:8890/netflix#"
    networks:
      - network-backend
  
  # Frontend (Node.js)
  node:
    build: './images/frontend/'
    volumes:
      - ./images/frontend/:/home/app/
      - /home/app/node_modules
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_SERVER=backend
      - DATABASE_URI=database
      - DATABASE_PORT=8890
    networks:
      - network-backend
      - network-frontend
    depends_on:
      - database

networks:
  network-backend:
    name: backend
    driver: bridge # Bridge ist Docker-Default.
    # internal: true # Wenn internal auf true gesetzt wird, ist das Netzwerk nicht mehr standardmäßig vom Host aufrufbar. Während Development noch hinderlich.
  network-frontend:
    name: frontend
    driver: bridge # Bridge ist Docker-Default.
